/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-05-16 14:36:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.manage.dashboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import admin.dashboard.DashboardSalesVO;
import admin.dashboard.DashboardOrderProgressVO;
import admin.dashboard.DashboardOrderVO;
import admin.dashboard.DashboardDAO;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  public java.lang.String getServletInfo() {
    return "";
  }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("admin.dashboard.DashboardDAO");
    _jspx_imports_classes.add("admin.dashboard.DashboardSalesVO");
    _jspx_imports_classes.add("admin.dashboard.DashboardOrderVO");
    _jspx_imports_classes.add("admin.dashboard.DashboardOrderProgressVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

Boolean isLoggedIn = (Boolean) session.getAttribute("isLoggedIn");

if (!Boolean.TRUE.equals(isLoggedIn)) {

      out.write("\n");
      out.write("  <script type=\"text/javascript\">\n");
      out.write("      alert('로그인이 필요합니다.');\n");
      out.write("      window.location.href = 'http://localhost/manage/adminLogin/adminLogin.jsp';\n");
      out.write("  </script>\n");

  return;
}

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../assets/jsp/admin/lib.jsp", out, false);
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("	$(function(){\n");
      out.write("    	$(\"#dashboard_menu\").addClass(\"bg-gradient-primary\");\n");
      out.write("	});\n");
      out.write("</script>\n");
      out.write("<!-- golgolz start -->\n");
      out.write("<link href=\"../../assets/css/manage/dashboard/index.css\" rel=\"stylesheet\" />\n");
      out.write("<style>\n");
      out.write(".dashboard-container{\n");
      out.write("	margin-left:24px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".chart_tit{\n");
      out.write("	margin-top: 20px;\n");
      out.write("	margin-bottom: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dashboard-container .chart_tit:first-child{\n");
      out.write("	margin-top:0px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<!-- golgolz end -->\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../assets/jsp/admin/header.jsp", out, false);
      out.write('\n');
      out.write('	');

		DashboardDAO dashboardDAO = DashboardDAO.getInstance();
		DashboardOrderVO orderVO = dashboardDAO.selectOrderInfo();	
		DashboardSalesVO salesVO = dashboardDAO.selectSalesInfo();
		DashboardOrderProgressVO progressVO = dashboardDAO.selectPregressInfo();
	
      out.write("\n");
      out.write("	<main\n");
      out.write("		class=\"main-content position-relative max-height-vh-100 h-100 border-radius-lg ps ps--active-y\">\n");
      out.write("		<nav\n");
      out.write("			class=\"navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl\"\n");
      out.write("			id=\"navbarBlur\" data-scroll=\"true\">\n");
      out.write("			<div class=\"container-fluid py-1 px-3\">\n");
      out.write("				<nav aria-label=\"breadcrumb\">\n");
      out.write("					<ol\n");
      out.write("						class=\"breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5\">\n");
      out.write("						<li class=\"breadcrumb-item text-sm\"><a\n");
      out.write("							class=\"opacity-5 text-dark\" href=\"javascript:;\">\n");
      out.write("							관리자 기능</a></li>\n");
      out.write("						<!-- 하단의 대시보드 텍스트를 본인 기능으로 변경 필요  -->\n");
      out.write("						<li class=\"breadcrumb-item text-sm text-dark active\"\n");
      out.write("							aria-current=\"page\">대시보드</li>\n");
      out.write("					</ol>\n");
      out.write("					<h6 class=\"font-weight-bolder mb-0\">대시보드</h6>\n");
      out.write("				</nav>\n");
      out.write("			</div>\n");
      out.write("		</nav>\n");
      out.write("		<div class=\"container-fluid py-4\">\n");
      out.write("			<!-- golgolz start -->\n");
      out.write("			<div class=\"dashboard-container\">\n");
      out.write("				<div class=\"chart_tit\">\n");
      out.write("	           		<h6 class=\"font-weight-bolder mb-0\">주문건수</h6>\n");
      out.write("	            </div>\n");
      out.write("	            <table class=\"chart_tb02\">\n");
      out.write("	            	<tbody>\n");
      out.write("						<tr>\n");
      out.write("	                    	<th scope=\"col\" width=\"310\">오늘</th>\n");
      out.write("	                     	<th scope=\"col\" width=\"310\">이번주</th>\n");
      out.write("	                      	<th scope=\"col\" width=\"310\">이번달</th>\n");
      out.write("	                  	</tr>\n");
      out.write("	                    <tr id=\"data_stat_month\" bgcolor=\"#f1f1f1\">\n");
      out.write("	                    	<td><strong>");
      out.print( orderVO.getToday() );
      out.write("건</strong></td>\n");
      out.write("	                      	<td><strong>");
      out.print( orderVO.getWeek() );
      out.write("건</strong></td>\n");
      out.write("	                      	<td><strong>");
      out.print( orderVO.getMonth() );
      out.write("건</strong></td>\n");
      out.write("	                  	</tr>\n");
      out.write("	             	</tbody>\n");
      out.write("	          	</table>\n");
      out.write("	          	<div class=\"chart_tit\">\n");
      out.write("	           		<h6 class=\"font-weight-bolder mb-0\">매출현황</h6>\n");
      out.write("	            </div>\n");
      out.write("	            <table class=\"chart_tb02\">\n");
      out.write("	            	<tbody>\n");
      out.write("						<tr>\n");
      out.write("	                    	<th scope=\"col\" width=\"310\">오늘</th>\n");
      out.write("	                     	<th scope=\"col\" width=\"310\">이번주</th>\n");
      out.write("	                      	<th scope=\"col\" width=\"310\">이번달</th>\n");
      out.write("	                  	</tr>\n");
      out.write("	                    <tr id=\"data_stat_month\" bgcolor=\"#f1f1f1\">\n");
      out.write("	                    	<td><strong>");
      out.print( salesVO.getToday() );
      out.write("원</strong></td>\n");
      out.write("	                      	<td><strong>");
      out.print( salesVO.getWeek() );
      out.write("원</strong></td>\n");
      out.write("	                      	<td><strong>");
      out.print( salesVO.getMonth() );
      out.write("원</strong></td>\n");
      out.write("	                  	</tr>\n");
      out.write("	             	</tbody>\n");
      out.write("	          	</table>\n");
      out.write("	          	<div class=\"chart_tit\">\n");
      out.write("	           		<h6 class=\"font-weight-bolder mb-0\">주문현황</h6>\n");
      out.write("	            </div>\n");
      out.write("	            <table class=\"chart_tb02\">\n");
      out.write("	            	<tbody>\n");
      out.write("						<tr>\n");
      out.write("	                    	<th scope=\"col\">주문완료</th>\n");
      out.write("	                     	<th scope=\"col\">배송준비</th>\n");
      out.write("	                      	<th scope=\"col\">배송중</th>\n");
      out.write("	                      	<th scope=\"col\">배송완료</th>\n");
      out.write("	                      	<th scope=\"col\">구매확정</th>\n");
      out.write("	                  	</tr>\n");
      out.write("	                    <tr id=\"data_stat_month\" bgcolor=\"#f1f1f1\">\n");
      out.write("	                    	<td><strong>");
      out.print( progressVO.getOrderDone() );
      out.write("건</strong></td>\n");
      out.write("	                      	<td><strong>");
      out.print( progressVO.getDeliveryReady() );
      out.write("건</strong></td>\n");
      out.write("	                      	<td><strong>");
      out.print( progressVO.getDeliveryInProgress() );
      out.write("건</strong></td>\n");
      out.write("	                      	<td><strong>");
      out.print( progressVO.getDeliveryDone() );
      out.write("건</strong></td>\n");
      out.write("	                      	<td><strong>");
      out.print( progressVO.getOrderConfirmed() );
      out.write("건</strong></td>\n");
      out.write("	                  	</tr>\n");
      out.write("	             	</tbody>\n");
      out.write("	          	</table>\n");
      out.write("	          	<div class=\"chart_tit\">\n");
      out.write("	           		<h6 class=\"font-weight-bolder mb-0\">반품현황</h6>\n");
      out.write("	            </div>\n");
      out.write("	            <table class=\"chart_tb02\">\n");
      out.write("	            	<tbody>\n");
      out.write("						<tr>\n");
      out.write("	                      	<th scope=\"col\" width=\"310\">반품건수</th>\n");
      out.write("	                  	</tr>\n");
      out.write("	                    <tr id=\"data_stat_month\" bgcolor=\"#f1f1f1\">\n");
      out.write("	                    	<td><strong>");
      out.print( orderVO.getRefund() );
      out.write("건</strong></td>\n");
      out.write("	                  	</tr>\n");
      out.write("	             	</tbody>\n");
      out.write("	          	</table>\n");
      out.write("			</div>\n");
      out.write("			<!-- golgolz end -->\n");
      out.write("		</div>\n");
      out.write("	</main>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
