/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-05-17 02:38:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.manage.review;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import admin.review.SearchVO;
import admin.review.ReviewBoardUtil;
import admin.review.ReviewBoardVO;
import java.util.List;
import admin.review.AdminReviewDAO;
import java.sql.SQLException;

public final class review_005fboard_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  public java.lang.String getServletInfo() {
    return "게시판 리스트";
  }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1715869714055L));
    _jspx_dependants.put("jar:file:/C:/dev/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/online-shop/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.sql.SQLException");
    _jspx_imports_classes.add("admin.review.ReviewBoardVO");
    _jspx_imports_classes.add("admin.review.SearchVO");
    _jspx_imports_classes.add("admin.review.ReviewBoardUtil");
    _jspx_imports_classes.add("admin.review.AdminReviewDAO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


Boolean isLoggedIn = (Boolean) session.getAttribute("isLoggedIn");
System.out.println("세션 로그인 상태: " + isLoggedIn);

if (!Boolean.TRUE.equals(isLoggedIn)) {


      out.write("\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("      alert('로그인이 필요합니다.');\r\n");
      out.write("      window.location.href = '../adminLogin/adminLogin.jsp'; // 경로 수정 필요\r\n");
      out.write("  </script>\r\n");

  return;
}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../assets/jsp/admin/lib.jsp", out, false);
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	$(function(){\r\n");
      out.write("    	$(\"#review_menu\").addClass(\"bg-gradient-primary\");\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("<!-- golgolz start -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://demo01.swm.whoismall.com/common/css/admin_community.css?v=202008110000\" type=\"text/css\" />\r\n");
      out.write("	<link href=\"https://demo01.swm.whoismall.com/common/css/bbs_data_naver.css?v=202008110000\" type=\"text/css\" rel=\"stylesheet\" >\r\n");
      out.write("<body class=\"mainlayout\">\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" height=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td height=\"125\" valign=\"top\"><link type=\"text/css\" href=\"https://demo01.swm.whoismall.com/common/css/admin_general.css?v=202008110000\" rel=\"stylesheet\">\r\n");
      out.write("<!-- golgolz end -->\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	#wrap{width: 1462px; height:749; margin:0px auto;}\r\n");
      out.write("	.num{width: 80px}\r\n");
      out.write("	.title{width: 350px}\r\n");
      out.write("	.id{width: 120px}\r\n");
      out.write("	.date{width: 150px}\r\n");
      out.write("	.cnt{width: 100px}\r\n");
      out.write("	    	\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("		$(function(){\r\n");
      out.write("			/* $(\"#search\").click(function(){\r\n");
      out.write("				chkNull();\r\n");
      out.write("			});//click */\r\n");
      out.write("			$(\"#btnAllSearch\").click(function(){\r\n");
      out.write("				location.href=\"review_board_list.jsp\";\r\n");
      out.write("			});//click\r\n");
      out.write("			$(\"#btnWrite\").click(function(){\r\n");
      out.write("				location.href=\"board_write_frm.jsp\";\r\n");
      out.write("			});//click\r\n");
      out.write("			\r\n");
      out.write("			$(\"#keyword\").keydown(function(evt) {\r\n");
      out.write("				if(evt.which ==13){\r\n");
      out.write("					chkNull();\r\n");
      out.write("				}//end if\r\n");
      out.write("			});//keydown\r\n");
      out.write("		\r\n");
      out.write("			$(\"#search\").click(function(){\r\n");
      out.write("				$(\"#frmBoard\").submit();\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("		});//ready\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		/*\r\n");
      out.write("		5,10,15,20을 눌렀을때 발생하는 함수 [테이블 새로 생성,]\r\n");
      out.write("		*/\r\n");
      out.write("		function changePageScale(){\r\n");
      out.write("			var selectOption = document.getElementById(\"list_num\").value;\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type: \"GET\",\r\n");
      out.write("				url: \"reviewTableAjax.jsp\",\r\n");
      out.write("				data: {\r\n");
      out.write("					selectOption: selectOption\r\n");
      out.write("				},\r\n");
      out.write("				success: function(data){\r\n");
      out.write("					displayTable(data);\r\n");
      out.write("				},\r\n");
      out.write("				error: function(xhr){\r\n");
      out.write("					alert(\"에러발생  : \" + xhr.status)\r\n");
      out.write("				}\r\n");
      out.write("			})\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function displayTable(data){\r\n");
      out.write("			var tbody = document.getElementById(\"tbody\");\r\n");
      out.write("			tbody.innerHTML=\"\";\r\n");
      out.write("			/* alert(data); */\r\n");
      out.write("			var object = JSON.parse(data);\r\n");
      out.write("			\r\n");
      out.write("			var boardList = object.boardList;\r\n");
      out.write("			\r\n");
      out.write("			for(var i=0 ; i < boardList.length; i++){\r\n");
      out.write("				var row = tbody.insertRow(i);\r\n");
      out.write("				\r\n");
      out.write("				//각속성에 대한 열 추가\r\n");
      out.write("				var cell1 = row.insertCell(0);\r\n");
      out.write("				var cell2 = row.insertCell(1);\r\n");
      out.write("				var cell3 = row.insertCell(2);\r\n");
      out.write("				var cell4 = row.insertCell(3);\r\n");
      out.write("				var cell5 = row.insertCell(4);\r\n");
      out.write("				var cell6 = row.insertCell(5);\r\n");
      out.write("				var cell7 = row.insertCell(6);\r\n");
      out.write("				\r\n");
      out.write("				 // 각 열에 체크박스 요소 추가\r\n");
      out.write("			    cell1.innerHTML = '<input type=\"checkbox\" name=\"checkbox' + i + '\">'; // 체크박스 추가\r\n");
      out.write("			    cell2.innerHTML = boardList[i].reviewId;\r\n");
      out.write("			    cell3.innerHTML = boardList[i].defaultImg;\r\n");
      out.write("			    cell4.innerHTML = boardList[i].name;\r\n");
      out.write("			    cell5.innerHTML = '<a href=\"review_board_list?seq=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rVO.reviewId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&currentPage=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty param.currentPage ?1:param.currentPage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">'+boardList[i].title+'</a>';\r\n");
      out.write("			    cell6.innerHTML = boardList[i].inputDate;\r\n");
      out.write("			    cell7.innerHTML = boardList[i].id;\r\n");
      out.write("			}//end for\r\n");
      out.write("			\r\n");
      out.write("			pagination(data);\r\n");
      out.write("			\r\n");
      out.write("		}//displayTable\r\n");
      out.write("		\r\n");
      out.write("		function pagination(data){\r\n");
      out.write("			\r\n");
      out.write("			var paging = document.getElementById(\"paging\");\r\n");
      out.write("			paging.innerHTML=\"\";\r\n");
      out.write("			\r\n");
      out.write("			var object = JSON.parse(data);\r\n");
      out.write("			var totalPage = object.totalPage;\r\n");
      out.write("			var currentPage = object.currentPage;\r\n");
      out.write("			\r\n");
      out.write("			$(\"#paging\").html(newPagination);\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		function chkNull() {\r\n");
      out.write("			if($(\"#keyword\").val().trim() !=\"\") {\r\n");
      out.write("				//alert(\"검색 키워드를 입력해주세요.\")\r\n");
      out.write("				$(\"#frmBoard\").submit();\r\n");
      out.write("				\r\n");
      out.write("			}//end if\r\n");
      out.write("		}//chkNull\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../assets/jsp/admin/header.jsp", out, false);
      out.write("\r\n");
      out.write("	<main\r\n");
      out.write("		class=\"main-content position-relative max-height-vh-100 h-100 border-radius-lg ps--active-y\">\r\n");
      out.write("		<nav\r\n");
      out.write("			class=\"navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl\"\r\n");
      out.write("			id=\"navbarBlur\" data-scroll=\"true\">\r\n");
      out.write("			<div class=\"container-fluid py-1 px-3\">\r\n");
      out.write("				<nav aria-label=\"breadcrumb\">\r\n");
      out.write("					<ol\r\n");
      out.write("						class=\"breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5\">\r\n");
      out.write("						<li class=\"breadcrumb-item text-sm\"><a\r\n");
      out.write("							class=\"opacity-5 text-dark\" href=\"http://192.168.10.211/manage/index.jsp\">\r\n");
      out.write("							관리자 기능</a></li>\r\n");
      out.write("						<!-- 하단의 대시보드 텍스트를 본인 기능으로 변경 필요  -->\r\n");
      out.write("						<li class=\"breadcrumb-item text-sm text-dark active\"\r\n");
      out.write("							aria-current=\"page\"><a href=\"http://192.168.10.211/manage/review/review.jsp\">리뷰 관리</a></li>\r\n");
      out.write("					</ol>\r\n");
      out.write("					<!-- <h6 class=\"font-weight-bolder mb-0\"><a href=\"http://192.168.10.211/manage/review/review.jsp\">리뷰 관리</a></h6> -->\r\n");
      out.write("				</nav>\r\n");
      out.write("			</div>\r\n");
      out.write("		</nav>\r\n");
      out.write("		<div class=\"container-fluid py-4\">\r\n");
      out.write("			<!-- golgolz start -->\r\n");
      out.write("<div id=\"wrap\">\r\n");
      out.write("<div id=\"content\">\r\n");
      out.write("	");

	request.setCharacterEncoding("UTF-8");
	
      out.write('\r');
      out.write('\n');
      admin.review.SearchVO sVO = null;
      sVO = (admin.review.SearchVO) _jspx_page_context.getAttribute("sVO", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (sVO == null){
        sVO = new admin.review.SearchVO();
        _jspx_page_context.setAttribute("sVO", sVO, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("sVO"), request);
      out.write('\r');
      out.write('\n');
      out.write('	');

	try{
	  /* String content=request.getParameter("keyword");
		System.out.print(content); */
		    AdminReviewDAO rDAO=AdminReviewDAO.getInstance();
		    //1.총 레코드 수 얻기
		    int totalCount = rDAO.selectTotalCount(sVO);
		    //2.한 화면에 보여줄 게시물의 수
		    int pageScale= 10;
		    //3.총 페이지 수
		    System.out.println(sVO+" / " +totalCount);
		    int totalPage=(int)Math.ceil((double)totalCount/pageScale);
		    System.out.println(sVO+" / " +totalPage);
		    //4.게시물의 시작번호
		    String tempPage=sVO.getCurrentPage();
		    /* System.out.println(totalPage); */
		    int currentPage=1;
		    if(tempPage !=null) {
		        try{
		        currentPage=Integer.parseInt(tempPage);
		        }catch(NumberFormatException nfe){
		        }
		    }//end if
		    int startNum=currentPage *pageScale-pageScale+1;
		    //5.게시물의 끝 번호
		    int endNum=startNum+pageScale-1;
		    
		    sVO.setStartNum(startNum);
		    sVO.setEndNum(endNum);
		    
		    List<ReviewBoardVO> list=rDAO.selectReviewBoard(sVO);//시작번호와 끝 번호 사이의 글 조회
		   	pageContext.setAttribute("list", list);
		    
		    pageContext.setAttribute("totalCount", totalCount);
		    pageContext.setAttribute("pageScale", pageScale);
		    pageContext.setAttribute("currentPage", currentPage);
		    
		    
	
      out.write("   \r\n");
      out.write("	    <div class=\"contents\">\r\n");
      out.write("		<!--begin of submain-->\r\n");
      out.write("		<form name=\"dataForm\" action=\"./\" method=\"post\">\r\n");
      out.write("		<input type=\"hidden\" name=\"act\"  value=\"community\">\r\n");
      out.write("		<input type=\"hidden\" name=\"ch\"   value=\"community\">\r\n");
      out.write("		<input type=\"hidden\" name=\"mode\" value=\"search\">\r\n");
      out.write("		<input type=\"hidden\" name=\"oc\"   value=\"\">\r\n");
      out.write("		<input type=\"hidden\" name=\"os\"   value=\"\">\r\n");
      out.write("		<input type=\"hidden\" name=\"bbs_code\"  value=\"user_review\">\r\n");
      out.write("		<input type=\"hidden\" name=\"bbs_mode\"  value=\"list\">\r\n");
      out.write("		<input type=\"hidden\" name=\"cate_code\" value=\"GD\">\r\n");
      out.write("		<input type=\"hidden\" name=\"seq\"  value=\"\">\r\n");
      out.write("		</form>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		<!-- 리스트 -->\r\n");
      out.write("		<!-- <div class=\"boxContainer\">\r\n");
      out.write("			<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" width=\"100%\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"left\"> \r\n");
      out.write("					</td>\r\n");
      out.write("					<td align=\"right\" class=\"right\">\r\n");
      out.write("						<select id=\"list_num\" name=\"list_num\" style=\"width:95px;\" onchange=\"changePageScale()\">\r\n");
      out.write("							<option value=\"5\" >5개 출력</option>\r\n");
      out.write("		                    <option value=\"10\" selected>10개 출력</option>\r\n");
      out.write("		                    <option value=\"20\">20개 출력</option>\r\n");
      out.write("		                    <option value=\"50\">50개 출력</option>\r\n");
      out.write("		                    <option value=\"100\">100개 출력</option>\r\n");
      out.write("						</select>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("		</div> -->\r\n");
      out.write("		\r\n");
      out.write("	   <div>\r\n");
      out.write("	    <table class=\"table\">\r\n");
      out.write("	    	<thead>\r\n");
      out.write("	    	<tr align=\"center\">\r\n");
      out.write("	    		<th class=\"thL\"><input type=\"checkbox\" id=\"check_all\" name=\"check_all\" value=\"bbs_seq[]\"></th>\r\n");
      out.write("	    		<th class=\"num\">번호</th>\r\n");
      out.write("	    		<th class=\"title\">이미지</th>\r\n");
      out.write("	    		<th class=\"title\">상품명</th>\r\n");
      out.write("	    		<th class=\"title\">제목</th>\r\n");
      out.write("	    		<th class=\"date\">작성일</th>\r\n");
      out.write("	    		<th class=\"id\">작성자</th>\r\n");
      out.write("<!-- 	    		<th class=\"cnt\">조회수</th> -->\r\n");
      out.write("	    	</tr>\r\n");
      out.write("	    	</thead>\r\n");
      out.write("	    	<tbody id=\"tbody\" align=\"center\">\r\n");
      out.write("	    		");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	    	</tbody>\r\n");
      out.write("	    </table>\r\n");
      out.write("	    \r\n");
      out.write("	   \r\n");
      out.write("	    \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("	    <div style=\"text-align: center;\">\r\n");
      out.write("	    <form action=\"review_board_list.jsp\" name=\"frmBoard\" id=\"frmBoard\" method=\"get\">\r\n");
      out.write("	    	<select name=\"field\" id=\"field\">\r\n");
      out.write("	    		<option value=\"0\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.field eq 0?\" selected='selected'\":\"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">제목</option>\r\n");
      out.write("	    		<option value=\"1\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.field eq 1?\" selected='selected'\":\"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">내용</option>\r\n");
      out.write("	    		");
      out.write("\r\n");
      out.write("	    	</select>\r\n");
      out.write("	    	<input type=\"text\" name=\"keyword\" id=\"keyword\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.keyword }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"width:230px; border:1px solid #dedede;\"/>\r\n");
      out.write("	    	<input type=\"button\"  value=\"검색\" id=\"search\" class=\"btn btn-info btn-sm\"/>\r\n");
      out.write("	    	<input type=\"button\"  value=\"전체글\" id=\"btnAllSearch\" class=\"btn btn-info btn-sm\" />\r\n");
      out.write("	    	<input type=\"text\" style=\"display: none;\">\r\n");
      out.write("	    </form>\r\n");
      out.write("	    </div>\r\n");
      out.write("	    \r\n");
      out.write("	    \r\n");
      out.write("	    \r\n");
      out.write("	    \r\n");
      out.write("	  <div style=\"text-align: center;\">\r\n");
      out.write("	  \r\n");
      out.write("	  ");

	  	  String param="";
	  		pageContext.setAttribute("param", param);
	  		pageContext.setAttribute("param", totalPage );
	  		pageContext.setAttribute("param", currentPage );
	  	  
      out.write("\r\n");
      out.write("        ");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f0_reused = false;
      try {
        _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f0.setParent(null);
        // /manage/review/review_board_list.jsp(319,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty param.keyword }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
        if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("        ");

        param="&field="+request.getParameter("field")+"&keyword="+request.getParameter("keyword");
        
            out.write("\r\n");
            out.write("            ");
            if (_jspx_meth_c_005fset_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("        ");
            int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
        _jspx_th_c_005fif_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
      }
      out.write("\r\n");
      out.write("        <div id=\"paging\">\r\n");
      out.write("        ");
      out.print(ReviewBoardUtil.getInstance().pageNation("review_board_list.jsp", param, totalPage, currentPage));
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    ");

		}catch (SQLException se){
			se.printStackTrace();
			out.println(".");
		}
	
      out.write("\r\n");
      out.write("	    </div>\r\n");
      out.write("	    \r\n");
      out.write("</div>\r\n");
      out.write("			<!-- golgolz end -->\r\n");
      out.write("</div>\r\n");
      out.write("	</main>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /manage/review/review_board_list.jsp(275,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("rVO");
      // /manage/review/review_board_list.jsp(275,7) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /manage/review/review_board_list.jsp(275,7) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("i");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("				<tr>\r\n");
            out.write("				");
            out.write("\r\n");
            out.write("				<td class=\"tdL\" align=\"center\"><input type=\"checkbox\" name=\"bbs_seq[]\" value=\"23\"></td>\r\n");
            out.write("				<td> ");
            if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("				<td><img src=\"http://192.168.10.211/assets/images/goods/");
            if (_jspx_meth_c_005fout_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\" style=\"width:60px; height:60px\"></td>\r\n");
            out.write("				<td> ");
            if (_jspx_meth_c_005fout_005f2(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("				<td><a href=\"review_detail_admin.jsp?reviewId=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rVO.reviewId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&currentPage=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty param.currentPage ?1:param.currentPage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            if (_jspx_meth_c_005fout_005f3(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</a></td>\r\n");
            out.write("				<td> ");
            if (_jspx_meth_c_005fout_005f4(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("				<td> ");
            if (_jspx_meth_c_005fout_005f5(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("				</tr>	    	\r\n");
            out.write("	    	");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /manage/review/review_board_list.jsp(279,9) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rVO.reviewId}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /manage/review/review_board_list.jsp(280,60) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rVO.defaultImg}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f2_reused = false;
    try {
      _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /manage/review/review_board_list.jsp(281,9) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rVO.name}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
      if (_jspx_th_c_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      _jspx_th_c_005fout_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f3_reused = false;
    try {
      _jspx_th_c_005fout_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /manage/review/review_board_list.jsp(282,128) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rVO.title}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f3 = _jspx_th_c_005fout_005f3.doStartTag();
      if (_jspx_th_c_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
      _jspx_th_c_005fout_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f4 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f4_reused = false;
    try {
      _jspx_th_c_005fout_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /manage/review/review_board_list.jsp(283,9) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rVO.inputDate}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f4 = _jspx_th_c_005fout_005f4.doStartTag();
      if (_jspx_th_c_005fout_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f4);
      _jspx_th_c_005fout_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f5 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f5_reused = false;
    try {
      _jspx_th_c_005fout_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /manage/review/review_board_list.jsp(284,9) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f5.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rVO.id}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f5 = _jspx_th_c_005fout_005f5.doStartTag();
      if (_jspx_th_c_005fout_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f5);
      _jspx_th_c_005fout_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /manage/review/review_board_list.jsp(323,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("link2");
      // /manage/review/review_board_list.jsp(323,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("&field=${param.field}&keyword=${param.keyword }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
