/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-06-10 06:43:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.companyInfo;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class user_005fcompany_005finfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  public java.lang.String getServletInfo() {
    return "";
  }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../assets/layout/user/lib.jsp", out, false);
      out.write("  \r\n");
      out.write("<!-- golgolz start -->\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link href=\"https://i.jobkorea.kr/content/css/ver_2/event/banner.promotion-sv-202401301659.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"https://i.jobkorea.kr//content/css/ver_2/modules/swiper/4.3.3/swiper.min.css?v=202405291400\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"https://i.jobkorea.kr/content/css/ver_2/common-sv-202405271315.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"https://i.jobkorea.kr/deploy/pc/dist/css/personal/common/gnb-sv-202405231305.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"https://i.jobkorea.kr/content/css/ver_1/salary/modules-sv-202401301659.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"https://i.jobkorea.kr/content/css/ver_1/salary/index-sv-202401301659.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"https://i.jobkorea.kr/deploy/pc/dist/css/personal/layout/footer-sv-202405131313.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("	<!-- golgolz end -->\r\n");
      out.write("<style text=\"text/css\">\r\n");
      out.write("	#btnSearchCompany{width:70px; height:40px; background-color:#FFFFFF; border:1px solid #333; margin-left:5px; font-size:15px}\r\n");
      out.write("</style>\r\n");
      out.write("<script text=\"text/javascript\">\r\n");
      out.write("	$(function(){\r\n");
      out.write("		<!-- golgolz start -->\r\n");
      out.write("		<!-- golgolz end -->\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"__next\" data-reactroot=\"\">\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../assets/layout/user/header.jsp", out, false);
      out.write("\r\n");
      out.write("		<main class=\"JobsFeed_Jobsfeed__DpeV9\">  \r\n");
      out.write("			<section class=\"Section_Section__P1hhc\">\r\n");
      out.write("			<!-- golgolz start -->\r\n");
      out.write("			<div>\r\n");
      out.write(" <form id=\"frmSearchCompany\" action=\"/Salary/Index#salarySearchCompany\" method=\"get\">\r\n");
      out.write("            <div class=\"row salarySearchCompany\" id=\"salarySearchCompany\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <!-- <i class=\"icon iconTop\" aria-hidden=\"true\"></i> -->\r\n");
      out.write("                    <div class=\"search searchCompany\">\r\n");
      out.write("                       <!--  <div class=\"description\"><em><strong>57</strong>만 기업</em>이 등록되어 있습니다.</div> -->\r\n");
      out.write("                       <!--  <div class=\"input inputSearch\" id=\"searchCommon\">\r\n");
      out.write("                            <label for=\"lbl_search\" class=\"skip\">검색</label>\r\n");
      out.write("                            <input id=\"txtCompanyName\" name=\"coKeyword\" placeholder=\"기업명을 검색해 보세요.\" type=\"text\" value=\"\" autocomplete=\"off\" />\r\n");
      out.write("                            <button id=\"btnSearchCompany\" type=\"button\" class=\"button buttonSearch\">검색</button> -->\r\n");
      out.write("                           <div class=\"popup\" aria-live=\"polite\" aria-hidden=\"true\" id=\"autocompletePane\">\r\n");
      out.write("                                <div class=\"noResult\" id=\"noResultPane\" style=\"display:none\">\r\n");
      out.write("                                    <p>검색 결과가 없음.</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"list\" id=\"recommendPane\" style=\"display:none\">\r\n");
      out.write("                                    <ul></ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"list\" id=\"resultPane\" style=\"display:none\">\r\n");
      out.write("                                    <ul></ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"popupFooter\" id=\"recommendButtonPane\" style=\"display:none\">\r\n");
      out.write("                                    <button type=\"button\" class=\"button buttonDeleteAll\"><span>전체삭제</span></button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"filter\" style=\"display: inline-block; text-align: left;\">\r\n");
      out.write("                        <div class=\"label\" style=\"display: inline-block; text-align: left;\">선택조건 검색</div>\r\n");
      out.write("                        <div class=\"buttons\" style=\"display: inline-block; text-align: left;\">\r\n");
      out.write("                            <button type=\"button\" class=\"button tab tab1 selected\" aria-selected=\"false\" data-tab=\"0\"><span>전체</span></button>\r\n");
      out.write("                            <button type=\"button\" class=\"button tab tab3\" aria-selected=\"true\" data-tab=\"2\"><span>직무별</span></button>\r\n");
      out.write("                            <select value=\"직무 선택\" style=\"margin-left:10px; margin-right:10px; width:100px; height:40px\">\r\n");
      out.write("                            	<option name=\"w1\" value=\"기획\">기획</option>\r\n");
      out.write("                            	<option name=\"w2\" value=\"법무\">법무</option>\r\n");
      out.write("                            	<option name=\"w3\" value=\"인사\">인사</option>\r\n");
      out.write("                            	<option name=\"w4\" value=\"회계\">회계</option>\r\n");
      out.write("                            	<option name=\"w5\" value=\"마케팅\">마케팅</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                            <!-- <input type=\"hidden\" name=\"tabindex\" id=\"hidTabIndex\" value=\"0\" /> -->\r\n");
      out.write("                             <div class=\"input inputSearch\" id=\"searchCommon\" style=\"width:300px\">\r\n");
      out.write("                            <input id=\"txtCompanyName\" name=\"coKeyword\" placeholder=\"기업명을 검색해 보세요.\" type=\"text\" value=\"\" autocomplete=\"off\" style=\"width:300px\"/>\r\n");
      out.write("                        	</div>\r\n");
      out.write("                            <input type=\"button\" id=\"btnSearchCompany\" value=\"검색\"/>\r\n");
      out.write("                       </div>\r\n");
      out.write("                        <div class=\"dropdown category3 hidden\" id=\"ddlJobType\" aria-hidden=\"true\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"jobTypeCode\" id=\"hidJobTypeCode\" value=\"\" />\r\n");
      out.write("                            <button type=\"button\" class=\"buttonChoose \" aria-haspopup=\"true\"><span>직무선택</span></button>\r\n");
      out.write("                            <!-- <div class=\"list\" aria-hidden=\"true\">\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><button type=\"button\"><span data-code=\"0\">직무선택</span></button></li>\r\n");
      out.write("                                        <li><button type=\"button\"><span data-code=\"10026\">기획&#183;전략</span></button></li>\r\n");
      out.write("                                        <li><button type=\"button\"><span data-code=\"10027\">법무&#183;사무&#183;총무</span></button></li>\r\n");
      out.write("                                        <li><button type=\"button\"><span data-code=\"10028\">인사&#183;HR</span></button></li>\r\n");
      out.write("                                        <li><button type=\"button\"><span data-code=\"10029\">회계&#183;세무</span></button></li>\r\n");
      out.write("                                        <li><button type=\"button\"><span data-code=\"10030\">마케팅&#183;광고&#183;MD</span></button></li>\r\n");
      out.write("                                        <li><button type=\"button\"><span data-code=\"10031\">개발&#183;데이터</span></button></li>\r\n");
      out.write("                                        <li><button type=\"button\"><span data-code=\"10032\">디자인</span></button></li>\r\n");
      out.write("                                        <li><button type=\"button\"><span data-code=\"10033\">물류&#183;무역</span></button></li>\r\n");
      out.write("                                        <li><button type=\"button\"><span data-code=\"10034\">운전&#183;운송&#183;배송</span></button></li>\r\n");
      out.write("                                        <li><button type=\"button\"><span data-code=\"10035\">영업</span></button></li>\r\n");
      out.write("                                        <li><button type=\"button\"><span data-code=\"10036\">고객상담&#183;TM</span></button></li>\r\n");
      out.write("                                        <li><button type=\"button\"><span data-code=\"10037\">금융&#183;보험</span></button></li>\r\n");
      out.write("                                        <li><button type=\"button\"><span data-code=\"10038\">식&#183;음료</span></button></li>\r\n");
      out.write("                                        <li><button type=\"button\"><span data-code=\"10039\">고객서비스&#183;리테일</span></button></li>\r\n");
      out.write("                                        <li><button type=\"button\"><span data-code=\"10040\">엔지니어링&#183;설계</span></button></li>\r\n");
      out.write("                                        <li><button type=\"button\"><span data-code=\"10041\">제조&#183;생산</span></button></li>\r\n");
      out.write("                                        <li><button type=\"button\"><span data-code=\"10042\">교육</span></button></li>\r\n");
      out.write("                                        <li><button type=\"button\"><span data-code=\"10043\">건축&#183;시설</span></button></li>\r\n");
      out.write("                                        <li><button type=\"button\"><span data-code=\"10044\">의료&#183;바이오</span></button></li>\r\n");
      out.write("                                        <li><button type=\"button\"><span data-code=\"10045\">미디어&#183;문화&#183;스포츠</span></button></li>\r\n");
      out.write("                                        <li><button type=\"button\"><span data-code=\"10046\">공공&#183;복지</span></button></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div> -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"row salaryList salaryCompanyList\">\r\n");
      out.write("                <input type=\"hidden\" id=\"hidMemChk\" value=\"0\" />\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"listHeader\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"total\">총 <em>572,139</em>건<span class=\"subtitle\">(전체 평균연봉)</span></div>\r\n");
      out.write("                        <!-- <div class=\"sort\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"haveAGI\" id=\"hidHaveAGI\" value=\"0\" />\r\n");
      out.write("                            <button type=\"button\" class=\"button buttonViewOnlyCompany \" id=\"btnHaveAGI\">\r\n");
      out.write("                                <span>채용중 기업만 보기</span>\r\n");
      out.write("                            </button>\r\n");
      out.write("                            <input type=\"hidden\" name=\"orderCode\" id=\"hidOrderCode\" value=\"2\" />\r\n");
      out.write("                            <div class=\"dropdown\" id=\"ddlSort\">\r\n");
      out.write("                                <button type=\"button\" class=\"buttonChoose\" aria-haspopup=\"true\"><span>인기검색순</span></button>\r\n");
      out.write("                                <div class=\"list\" aria-hidden=\"true\">\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><button type=\"button\"><span data-index=\"2\">인기검색순</span></button></li>\r\n");
      out.write("                                        <li><button type=\"button\"><span data-index=\"1\">업데이트순</span></button></li>\r\n");
      out.write("                                        <li><button type=\"button\"><span data-index=\"3\">평균연봉 높은순</span></button></li>\r\n");
      out.write("                                        \r\n");
      out.write("                                        <li><button type=\"button\"><span data-index=\"5\">사원 많은순</span></button></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div> -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"noData\" id=\"listNoData\"   style=\"display:none\"  >\r\n");
      out.write("\r\n");
      out.write("                        <p><strong>‘직무선택’</strong>에 대한 검색결과가 없습니다.<br>다른 검색어로 검색해주세요.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <ul class=\"list\" id=\"listCompany\" >\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"/Company/1696583/Salary?C_IDX=1\" target=\"_blank\">\r\n");
      out.write("                                        <div class=\"thumbnail\">\r\n");
      out.write("                                            <img src=\"//imgs.jobkorea.co.kr/img1/_whitebg/200X80/Co_Logo/Logo/2023/9/09/JK_CO_msyvfp23090915182940.jpg?v=202406041618\" onerror=\"companylogoOnError('/salary/logourl?ucono=1696583' , this)\">\r\n");
      out.write("                                            <div class=\"inner\">삼성전자㈜</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    <div class=\"headers\">\r\n");
      out.write("                                        <div class=\"text\">삼성전자㈜</div>\r\n");
      out.write("                                            <button type=\"button\" class=\"button buttonFavorites\" onclick=\"jk.biz.core.layerlogin.loginCheckAndGo(null, this, [], '/Salary/Index#listCompany', 1);return false;\" data-mem-sys=\"\">좋아요</button>\r\n");
      out.write("                                                                            </div>\r\n");
      out.write("                                    <div class=\"summary\">\r\n");
      out.write("                                                                                    <div class=\"item\">매출액 170조 3천억원</div>\r\n");
      out.write("                                                                                    <div class=\"item\">사원수 124,404명</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"salary\">\r\n");
      out.write("                                        <div class=\"inner\"><strong>10,377</strong>만원</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"/Company/1360583/Salary?C_IDX=7\" target=\"_blank\">\r\n");
      out.write("                                        <div class=\"thumbnail\">\r\n");
      out.write("                                            <img src=\"//imgs.jobkorea.co.kr/img1/_whitebg/200X80/Co_Logo/Logo/2016/13/2x9an00bXu_cGpzromp2d3g26u0hnVfRd_akkj2qnu.jpg?v=202406041618&amp;hash=r&amp;serviceCode=CL\" onerror=\"companylogoOnError('/salary/logourl?ucono=1360583' , this)\">\r\n");
      out.write("                                            <div class=\"inner\">현대자동차㈜</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    <div class=\"headers\">\r\n");
      out.write("                                        <div class=\"text\">현대자동차㈜</div>\r\n");
      out.write("                                            <button type=\"button\" class=\"button buttonFavorites\" onclick=\"jk.biz.core.layerlogin.loginCheckAndGo(null, this, [], '/Salary/Index#listCompany', 1);return false;\" data-mem-sys=\"\">좋아요</button>\r\n");
      out.write("                                                                                    <div class=\"badge\">채용중</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"summary\">\r\n");
      out.write("                                            <div class=\"item\">자동차&#183;조선&#183;철강&#183;항공</div>\r\n");
      out.write("                                                                                    <div class=\"item\">매출액 78조 3백억원</div>\r\n");
      out.write("                                                                                    <div class=\"item\">사원수 73,500명</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"salary\">\r\n");
      out.write("                                        <div class=\"inner\"><strong>11,742</strong>만원</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"/Company/1517115/Salary?C_IDX=2167\" target=\"_blank\">\r\n");
      out.write("                                        <div class=\"thumbnail\">\r\n");
      out.write("                                            <img src=\"//imgs.jobkorea.co.kr/img1/_whitebg/200X80/Co_Logo/Logo/2023/6/23/JK_CO_kXmqMBL23062314335619.png?v=202406041618\" onerror=\"companylogoOnError('/salary/logourl?ucono=1517115' , this)\">\r\n");
      out.write("                                            <div class=\"inner\">잡코리아(유)</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    <div class=\"headers\">\r\n");
      out.write("                                        <div class=\"text\">잡코리아(유)</div>\r\n");
      out.write("                                            <button type=\"button\" class=\"button buttonFavorites\" onclick=\"jk.biz.core.layerlogin.loginCheckAndGo(null, this, [], '/Salary/Index#listCompany', 1);return false;\" data-mem-sys=\"\">좋아요</button>\r\n");
      out.write("                                                                                    <div class=\"badge\">채용중</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"summary\">\r\n");
      out.write("                                            <div class=\"item\">포털&#183;컨텐츠&#183;커뮤니티</div>\r\n");
      out.write("                                                                                                                            <div class=\"item\">사원수 530명</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"salary\">\r\n");
      out.write("                                        <div class=\"inner\"><strong>6,132</strong>만원</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"/Company/1508733/Salary?C_IDX=354\" target=\"_blank\">\r\n");
      out.write("                                        <div class=\"thumbnail\">\r\n");
      out.write("                                            <img src=\"//imgs.jobkorea.co.kr/img1/_whitebg/200X80/Co_Logo/Logo/2022/1/06/JK_CO_YMc0NQg22010611014030.jpg?v=202406041618\" onerror=\"companylogoOnError('/salary/logourl?ucono=1508733' , this)\">\r\n");
      out.write("                                            <div class=\"inner\">하이트진로㈜</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    <div class=\"headers\">\r\n");
      out.write("                                        <div class=\"text\">하이트진로㈜</div>\r\n");
      out.write("                                            <button type=\"button\" class=\"button buttonFavorites\" onclick=\"jk.biz.core.layerlogin.loginCheckAndGo(null, this, [], '/Salary/Index#listCompany', 1);return false;\" data-mem-sys=\"\">좋아요</button>\r\n");
      out.write("                                                                            </div>\r\n");
      out.write("                                    <div class=\"summary\">\r\n");
      out.write("                                            <div class=\"item\">식품가공</div>\r\n");
      out.write("                                                                                    <div class=\"item\">매출액 2조 2,467억원</div>\r\n");
      out.write("                                                                                    <div class=\"item\">사원수 3,013명</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"salary\">\r\n");
      out.write("                                        <div class=\"inner\"><strong>11,250</strong>만원</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"/Company/1532033/Salary?C_IDX=6021\" target=\"_blank\">\r\n");
      out.write("                                        <div class=\"thumbnail\">\r\n");
      out.write("                                            <img src=\"//imgs.jobkorea.co.kr/img1/_whitebg/200X80/Co_Logo/Logo/2016/10/2w3bs008Rw_eXiu3zl3d24w0esYbUq_vx2sw.gif?v=202406041618&amp;hash=r&amp;serviceCode=CL\" onerror=\"companylogoOnError('/salary/logourl?ucono=1532033' , this)\">\r\n");
      out.write("                                            <div class=\"inner\">쿠팡</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    <div class=\"headers\">\r\n");
      out.write("                                        <div class=\"text\">쿠팡</div>\r\n");
      out.write("                                            <button type=\"button\" class=\"button buttonFavorites\" onclick=\"jk.biz.core.layerlogin.loginCheckAndGo(null, this, [], '/Salary/Index#listCompany', 1);return false;\" data-mem-sys=\"\">좋아요</button>\r\n");
      out.write("                                                                                    <div class=\"badge\">채용중</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"summary\">\r\n");
      out.write("                                            <div class=\"item\">쇼핑몰&#183;오픈마켓&#183;소셜커머스</div>\r\n");
      out.write("                                                                                    <div class=\"item\">매출액 4조 4227억원</div>\r\n");
      out.write("                                                                                    <div class=\"item\">사원수 6,372명</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"salary\">\r\n");
      out.write("                                        <div class=\"inner\"><strong>5,011</strong>만원</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"/Company/1710438/Salary?C_IDX=1258\" target=\"_blank\">\r\n");
      out.write("                                        <div class=\"thumbnail\">\r\n");
      out.write("                                            <img src=\"//imgs.jobkorea.co.kr/img1/_whitebg/200X80/Co_Logo/Logo/2021/10/21/2q1jz007Pq_qWla2i3a2oq0dzMjSz_uqzq.jpg?v=202406041618&amp;hash=r&amp;serviceCode=CL\" onerror=\"companylogoOnError('/salary/logourl?ucono=1710438' , this)\">\r\n");
      out.write("                                            <div class=\"inner\">㈜하나투어</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    <div class=\"headers\">\r\n");
      out.write("                                        <div class=\"text\">㈜하나투어</div>\r\n");
      out.write("                                            <button type=\"button\" class=\"button buttonFavorites\" onclick=\"jk.biz.core.layerlogin.loginCheckAndGo(null, this, [], '/Salary/Index#listCompany', 1);return false;\" data-mem-sys=\"\">좋아요</button>\r\n");
      out.write("                                                                                    <div class=\"badge\">채용중</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"summary\">\r\n");
      out.write("                                            <div class=\"item\">호텔&#183;여행&#183;항공</div>\r\n");
      out.write("                                                                                                                            <div class=\"item\">사원수 1,297명</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"salary\">\r\n");
      out.write("                                        <div class=\"inner\"><strong>4,542</strong>만원</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"/Company/1385349/Salary?C_IDX=8\" target=\"_blank\">\r\n");
      out.write("                                        <div class=\"thumbnail\">\r\n");
      out.write("                                            <img src=\"//imgs.jobkorea.co.kr/img1/_whitebg/200X80/Co_Logo/Logo/2017/6/2130s008R-_4X9u1963523-0esY8U6_5-2s-.jpg?v=202406041618&amp;hash=r&amp;serviceCode=CL\" onerror=\"companylogoOnError('/salary/logourl?ucono=1385349' , this)\">\r\n");
      out.write("                                            <div class=\"inner\">엘지전자㈜</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    <div class=\"headers\">\r\n");
      out.write("                                        <div class=\"text\">엘지전자㈜</div>\r\n");
      out.write("                                            <button type=\"button\" class=\"button buttonFavorites\" onclick=\"jk.biz.core.layerlogin.loginCheckAndGo(null, this, [], '/Salary/Index#listCompany', 1);return false;\" data-mem-sys=\"\">좋아요</button>\r\n");
      out.write("                                                                                    <div class=\"badge\">채용중</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"summary\">\r\n");
      out.write("                                            <div class=\"item\">전기&#183;전자&#183;제어</div>\r\n");
      out.write("                                                                                    <div class=\"item\">매출액 28조 8천억원</div>\r\n");
      out.write("                                                                                    <div class=\"item\">사원수 35,055명</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"salary\">\r\n");
      out.write("                                        <div class=\"inner\"><strong>8,498</strong>만원</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"/Company/1834120/Salary?C_IDX=21\" target=\"_blank\">\r\n");
      out.write("                                        <div class=\"thumbnail\">\r\n");
      out.write("                                            <img src=\"//imgs.jobkorea.co.kr/img1/_whitebg/200X80/Co_Logo/Logo/2019/7/2a3fc008Rw_hXifqag3d2ww0ecYrUr_cx2cw.jpg?v=202406041618&amp;hash=r&amp;serviceCode=CL\" onerror=\"companylogoOnError('/salary/logourl?ucono=1834120' , this)\">\r\n");
      out.write("                                            <div class=\"inner\">SOIL</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    <div class=\"headers\">\r\n");
      out.write("                                        <div class=\"text\">SOIL</div>\r\n");
      out.write("                                            <button type=\"button\" class=\"button buttonFavorites\" onclick=\"jk.biz.core.layerlogin.loginCheckAndGo(null, this, [], '/Salary/Index#listCompany', 1);return false;\" data-mem-sys=\"\">좋아요</button>\r\n");
      out.write("                                                                            </div>\r\n");
      out.write("                                    <div class=\"summary\">\r\n");
      out.write("                                            <div class=\"item\">화학&#183;에너지&#183;환경</div>\r\n");
      out.write("                                                                                    <div class=\"item\">매출액 35조 2천억원</div>\r\n");
      out.write("                                                                                    <div class=\"item\">사원수 3,174명</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"salary\">\r\n");
      out.write("                                        <div class=\"inner\"><strong>17,109</strong>만원</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"http://localhost/recruit-app/companyInfo/user_company_detail.jsp\" target=\"_blank\">\r\n");
      out.write("                                        <div class=\"thumbnail\">\r\n");
      out.write("                                            <img src=\"//imgs.jobkorea.co.kr/img1/_whitebg/200X80/Co_Logo/Logo/2011/10/2w1aj007Pm_gWzi2y3i2jm0djMcSj_ldjm.gif?v=202406041618&amp;hash=r&amp;serviceCode=CL\" onerror=\"companylogoOnError('/salary/logourl?ucono=1882711' , this)\">\r\n");
      out.write("                                            <div class=\"inner\">넥슨코리아</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    <div class=\"headers\">\r\n");
      out.write("                                        <div class=\"text\">넥슨코리아</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"summary\">\r\n");
      out.write("                                            <div class=\"item\">컴퓨터&#183;하드웨어&#183;장비</div>\r\n");
      out.write("                                                                                    <div class=\"item\">매출액 3조 9000억</div>\r\n");
      out.write("                                                                                    <div class=\"item\">사원수 3,500명</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"salary\">\r\n");
      out.write("                                        <div class=\"inner\"><strong>6,751</strong>만원</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"/Company/1487996/Salary?C_IDX=39\" target=\"_blank\">\r\n");
      out.write("                                        <div class=\"thumbnail\">\r\n");
      out.write("                                            <img src=\"//imgs.jobkorea.co.kr/img1/_whitebg/200X80/Co_Logo/Logo/2022/13/2539s008R-_2X0u8923829-0esY8U9_8-2s-.gif?v=202406041618&amp;hash=r&amp;serviceCode=CL\" onerror=\"companylogoOnError('/salary/logourl?ucono=1487996' , this)\">\r\n");
      out.write("                                            <div class=\"inner\">대한항공</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    <div class=\"headers\">\r\n");
      out.write("                                        <div class=\"text\">대한항공</div>\r\n");
      out.write("                                            <button type=\"button\" class=\"button buttonFavorites\" onclick=\"jk.biz.core.layerlogin.loginCheckAndGo(null, this, [], '/Salary/Index#listCompany', 1);return false;\" data-mem-sys=\"\">좋아요</button>\r\n");
      out.write("                                                                            </div>\r\n");
      out.write("                                    <div class=\"summary\">\r\n");
      out.write("                                            <div class=\"item\">자동차&#183;조선&#183;철강&#183;항공</div>\r\n");
      out.write("                                                                                    <div class=\"item\">매출액 14조 5천억원</div>\r\n");
      out.write("                                                                                    <div class=\"item\">사원수 17,931명</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"salary\">\r\n");
      out.write("                                        <div class=\"inner\"><strong>9,806</strong>만원</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"/Company/1976007/Salary?C_IDX=924\" target=\"_blank\">\r\n");
      out.write("                                        <div class=\"thumbnail\">\r\n");
      out.write("                                            <img src=\"//imgs.jobkorea.co.kr/img1/_whitebg/200X80/Co_Logo/Logo/2020/12/16/2v7pq00aRn_zKldafzno3j2wn0gqYeIm_vpnw2qn.gif?v=202406041618&amp;hash=r&amp;serviceCode=CL\" onerror=\"companylogoOnError('/salary/logourl?ucono=1976007' , this)\">\r\n");
      out.write("                                            <div class=\"inner\">카카오</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    <div class=\"headers\">\r\n");
      out.write("                                        <div class=\"text\">카카오</div>\r\n");
      out.write("                                            <button type=\"button\" class=\"button buttonFavorites\" onclick=\"jk.biz.core.layerlogin.loginCheckAndGo(null, this, [], '/Salary/Index#listCompany', 1);return false;\" data-mem-sys=\"\">좋아요</button>\r\n");
      out.write("                                                                                    <div class=\"badge\">채용중</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"summary\">\r\n");
      out.write("                                            <div class=\"item\">포털&#183;컨텐츠&#183;커뮤니티</div>\r\n");
      out.write("                                                                                    <div class=\"item\">매출액 2조 4,995억원</div>\r\n");
      out.write("                                                                                    <div class=\"item\">사원수 3,680명</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"salary\">\r\n");
      out.write("                                        <div class=\"inner\"><strong>10,209</strong>만원</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"/Company/16154114/Salary?C_IDX=8696\" target=\"_blank\">\r\n");
      out.write("                                        <div class=\"thumbnail\">\r\n");
      out.write("                                            <img src=\"//imgs.jobkorea.co.kr/img1/_whitebg/200X80/Co_Logo/Logo/2022/9/16/JK_CO_Gv7v7T422091611283337.JPG?v=202406041618\" onerror=\"companylogoOnError('/salary/logourl?ucono=16154114' , this)\">\r\n");
      out.write("                                            <div class=\"inner\">메가스터디교육</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    <div class=\"headers\">\r\n");
      out.write("                                        <div class=\"text\">메가스터디교육</div>\r\n");
      out.write("                                            <button type=\"button\" class=\"button buttonFavorites\" onclick=\"jk.biz.core.layerlogin.loginCheckAndGo(null, this, [], '/Salary/Index#listCompany', 1);return false;\" data-mem-sys=\"\">좋아요</button>\r\n");
      out.write("                                                                                    <div class=\"badge\">채용중</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"summary\">\r\n");
      out.write("                                            <div class=\"item\">학원&#183;어학원&#183;교육원</div>\r\n");
      out.write("                                                                                    <div class=\"item\">매출액 8,356억</div>\r\n");
      out.write("                                                                                    <div class=\"item\">사원수 1,700명</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"salary\">\r\n");
      out.write("                                        <div class=\"inner\"><strong>4,177</strong>만원</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"paginations\" role=\"navigation\" id=\"listPaging\" >\r\n");
      out.write("                        <input type=\"hidden\" id=\"hidCoPage\" name=\"coPage\" value=\"1\" />\r\n");
      out.write("                                                        <strong class=\"item active\">1</strong>\r\n");
      out.write("                               <!--  <a href=\"#\" class=\"item\" data-page=\"2\">2</a>\r\n");
      out.write("                                <a href=\"#\" class=\"item\" data-page=\"3\">3</a>\r\n");
      out.write("                                <a href=\"#\" class=\"item\" data-page=\"4\">4</a>\r\n");
      out.write("                                <a href=\"#\" class=\"item\" data-page=\"5\">5</a>\r\n");
      out.write("                                <a href=\"#\" class=\"item\" data-page=\"6\">6</a>\r\n");
      out.write("                                <a href=\"#\" class=\"item\" data-page=\"7\">7</a>\r\n");
      out.write("                                <a href=\"#\" class=\"item\" data-page=\"8\">8</a>\r\n");
      out.write("                                <a href=\"#\" class=\"item\" data-page=\"9\">9</a>\r\n");
      out.write("                                <a href=\"#\" class=\"item\" data-page=\"10\">10</a> -->\r\n");
      out.write("\r\n");
      out.write("                            <!-- <a href=\"#\" class=\"item next\" data-page=\"11\">다음</a> -->\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("			\r\n");
      out.write("			<!-- golgolz end -->\r\n");
      out.write("			</section>\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../assets/layout/user/footer.jsp", out, false);
      out.write("  \r\n");
      out.write("		</main>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
