/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-05-17 00:17:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.review;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import user.review.UserReviewDAO;
import admin.review.ReviewBoardVO;
import java.util.List;
import java.sql.SQLException;

public final class review_005fdetail_005fuser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  public java.lang.String getServletInfo() {
    return "게시판 글 읽기";
  }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1715869714055L));
    _jspx_dependants.put("jar:file:/C:/dev/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/online-shop/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/C:/dev/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/online-shop/WEB-INF/lib/standard.jar!/META-INF/fmt.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("user.review.UserReviewDAO");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.sql.SQLException");
    _jspx_imports_classes.add("admin.review.ReviewBoardVO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

ReviewBoardVO rVO=new ReviewBoardVO();
String userId = (String) session.getAttribute("userId");


if (userId == null) {
    System.out.println("로그인이 필요합니다. ");

      out.write("\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        alert('로그인이 필요합니다.');\r\n");
      out.write("        window.location.href = '../user/login/userLogin.jsp'; // 경로 수정 필요\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");

    return;
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../assets/jsp/user/lib.jsp", out, false);
      out.write("\r\n");
      out.write("	<!-- golgolz start -->\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://img.echosting.cafe24.com/editors/froala/css/froala_style_ec.min.css?vs=2404251304\" charset=\"utf-8\"/>\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://insideobject.com/ind-script/optimizer.php?filename=nZExDgIxDAT7KC3vsOAJPIEfOMFwJxJv5DgS_J6jggYJ0o52doulBVVofzBqhqtxJZOOYVko904Xgzpl1AqNG9jRL3nJoaMMX6Eh4T4pDvfZ0cIPsTnVORWZVNFCWVVCYtWv-9waHcF2ptNn3YZjeuGYCvJtVjZpMP_Pft_7BA&type=css&k=ecd691e0c80070ef935d0e961272742f67437a3c&t=1681776733\"/>\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://insideobject.com/ind-script/optimizer_user.php?filename=tdRLTsQwDAbgfcuWc3hGiHsgcYI83NYaJ47ipDC3J2UQiHWTXR7V5-iXa9gkIKCbq2JWYFqQjb28XK6QqmVy81YCg3qcPSqtEfRG8foKThWC-MoIVkz2kNH4N-NuZsWndvkM3WQnIWAsY_AgOx56Z5ZJi65ZauoMLzW6QhLPsWzuUgtYo-S-axwZd0cfB51RdFPb4FRpEFxEuFAapG_Io-iUW6O4UXkns1I0BUelbuwg2dZSurf2Ly6f4wLhUWG3z9w52i8skiFxbV3RdlPGnfDjbzXo5e0Cc7eR-lMm1PbD6ybpfaOUKK69CziJezPa2E4ncw-SMe73R40eQ_s_qHpoXw&type=css&k=0098db34b7f7c0214e4a2bddabcfc92b64957ce4&t=1678165953&user=T\"/>\r\n");
      out.write("	<!-- golgolz end -->\r\n");
      out.write("  \r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	#wrap{width: 1462px; height:749; margin:0px auto;}\r\n");
      out.write("\r\n");
      out.write("	    	\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	$(function(){\r\n");
      out.write("	    $(\"#btnUpdate\").click(function () {\r\n");
      out.write("	    	if(confirm(\"글을 수정하시겠습니까?\")){\r\n");
      out.write("	    	chkNull();	    		\r\n");
      out.write("	    	}//end if\r\n");
      out.write("	    });//click\r\n");
      out.write("	    $(\"#btnDelete\").click(function () {\r\n");
      out.write("			if(confirm(\"글을 정말 삭제하시겠습니까?\")){\r\n");
      out.write("	    	//<form태그의 action 변경\r\n");
      out.write("	    	//var frm=document.frmDetail.action=\"back-end URL\"\r\n");
      out.write("	    	$(\"#frmDetail\")[0].action=\"review_delete_process.jsp\";\r\n");
      out.write("	    	$(\"#frmDetail\").submit();\r\n");
      out.write("			}//end if\r\n");
      out.write("	    \r\n");
      out.write("	    });//click\r\n");
      out.write("	});//ready\r\n");
      out.write("	\r\n");
      out.write("	function chkNull() {\r\n");
      out.write("	    if($(\"#title\").val().trim() == \"\") {\r\n");
      out.write("	        alert(\"글 제목은 필수입력\");\r\n");
      out.write("	        $(\"#title\").focus();\r\n");
      out.write("	        return;\r\n");
      out.write("	    }//end if\r\n");
      out.write("	    if($(\"#content\").val().trim() == \"\") {\r\n");
      out.write("	        alert(\"내용은 필수입력\");\r\n");
      out.write("	        $(\"#content\").focus();\r\n");
      out.write("	        return;\r\n");
      out.write("	    }//end if\r\n");
      out.write("	    if($(\"#cnt\").val().trim() == \"\") {\r\n");
      out.write("	        $(\"#cnt\").val(0);\r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("	    $(\"#frmDetail\")[0].action=\"review_update_process.jsp\";\r\n");
      out.write("	    $(\"#frmDetail\").submit();\r\n");
      out.write("	\r\n");
      out.write("	}//chkNull\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("	\r\n");
      out.write("      $('#content').summernote({\r\n");
      out.write("        tabsize: 2,\r\n");
      out.write("        width:600,\r\n");
      out.write("        height: 200,\r\n");
      out.write("        toolbar: [\r\n");
      out.write("          ['style', ['style']],\r\n");
      out.write("          ['font', ['bold', 'underline', 'clear']],\r\n");
      out.write("          ['color', ['color']],\r\n");
      out.write("          ['para', ['ul', 'ol', 'paragraph']],\r\n");
      out.write("          ['table', ['table']],\r\n");
      out.write("          ['insert', ['link', 'picture', 'video']],\r\n");
      out.write("          ['view', ['fullscreen', 'codeview', 'help']]\r\n");
      out.write("        ]\r\n");
      out.write("      });//summernote\r\n");
      out.write("})//ready\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../assets/jsp/user/header.jsp", out, false);
      out.write("\r\n");
      out.write("	<div id=\"wrap\">\r\n");
      out.write("		<div id=\"main\">\r\n");
      out.write("			<!-- golgolz start -->\r\n");
      out.write("			<div class=\"titleArea\">\r\n");
      out.write("            <h2><font color=\"#555555\">REVIEW</font> </h2>\r\n");
      out.write("            <p>상품 사용후기입니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"wrap\">\r\n");
      out.write("<div id=\"boardContent\">\r\n");

	UserReviewDAO rDAO=UserReviewDAO.getInstance();
	try{
	  String seq=request.getParameter("reviewId");
	  
	  rVO=rDAO.selectDetailReview(Integer.parseInt(seq));//상세보기
	 /*  rDAO.updateCnt(Integer.parseInt(seq)); *///조회수 올려주기(중요도가 덜한것이 아래로 내려가는게 좋음)
	 System.out.print(seq); 
	 
	  pageContext.setAttribute("rVO", rVO);
	}catch(SQLException se){
	  se.printStackTrace();
	  out.print("sql 에러");
	}

      out.write("\r\n");
      out.write("<div class=\"xans-element- xans-board xans-board-product-4 xans-board-product xans-board-4 ec-base-box typeProduct \">\r\n");
      out.write("<p class=\"thumbnail\">\r\n");
      out.write("<a href=\"#\"><img src=\"http://localhost/assets/images/goods/");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("\" style=\"width:60px; height:60px\"\"/></a></p>\r\n");
      out.write("<div class=\"information\"  style=\"padding-left:20px\">\r\n");
      out.write("            <h3><a href=\"#\"> ");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("</a></h3>\r\n");
      out.write("        </div>\r\n");
      out.write("</div>\r\n");
      out.write("<form id=\"frmDetail\" name=\"frmDetail\" action=\"review_delete_process.jsp\" method=\"post\" target=\"_self\" enctype=\"multipart/form-data\" >\r\n");
      out.write("<input id=\"no\" name=\"no\" value=\"28387\" type=\"hidden\"  />\r\n");
      out.write("<input id=\"bulletin_no\" name=\"bulletin_no\" value=\"29332\" type=\"hidden\"  />\r\n");
      out.write("<input id=\"board_no\" name=\"board_no\" value=\"4\" type=\"hidden\"  />\r\n");
      out.write("<input id=\"member_id\" name=\"member_id\" value=\"\" type=\"hidden\"  />\r\n");
      out.write("<input id=\"list_url\" name=\"list_url\" value=\"/board/product/list.html?board_no=4\" type=\"hidden\"  />\r\n");
      out.write("<input id=\"bdf_modify_url\" name=\"bdf_modify_url\" value=\"/board/product/modify.html?board_act=edit&amp;no=28387&amp;board_no=4\" type=\"hidden\"  />\r\n");
      out.write("<input id=\"bdf_del_url\" name=\"bdf_del_url\" value=\"/exec/front/Board/del/4\" type=\"hidden\"  />\r\n");
      out.write("<input id=\"bdf_action_type\" name=\"bdf_action_type\" value=\"\" type=\"hidden\"  />\r\n");
      out.write("<input type=\"hidden\" name=\"reviewId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rVO.reviewId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("<div class=\"xans-element- xans-board xans-board-read-4 xans-board-read xans-board-4\">\r\n");
      out.write("<!--        $login_page_url = /member/login.html\r\n");
      out.write("            $deny_access_url = /board/product/list.html\r\n");
      out.write("        -->\r\n");
      out.write("<div class=\"ec-base-table typeWrite \">\r\n");
      out.write("            <table border=\"1\" summary=\"\">\r\n");
      out.write("<caption>상품 게시판 상세</caption>\r\n");
      out.write("            <colgroup>\r\n");
      out.write("<col style=\"width:130px;\"/>\r\n");
      out.write("<col style=\"width:auto;\"/>\r\n");
      out.write("</colgroup>\r\n");
      out.write("<tbody>\r\n");
      out.write("<tr>\r\n");
      out.write("<th scope=\"row\">제목</th>\r\n");
      out.write("                    <td><strong>");
      if (_jspx_meth_c_005fout_005f2(_jspx_page_context))
        return;
      out.write("</strong></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<th scope=\"row\">작성자</th>\r\n");
      out.write("                    <td><strong>");
      if (_jspx_meth_c_005fout_005f3(_jspx_page_context))
        return;
      out.write("</strong></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td colspan=\"2\">\r\n");
      out.write("                        <ul class=\"etcArea\">\r\n");
      out.write("                             </li>\r\n");
      out.write("                            <li class=\"\">\r\n");
      out.write("                                <strong>작성일</strong> ");
      if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("<div class=\"detail\"><div class=\"fr-view fr-view-article\">");
      if (_jspx_meth_c_005fout_005f4(_jspx_page_context))
        return;
      out.write("</div></div>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("<tr class=\"attach displaynone\">\r\n");
      out.write("<th scope=\"row\">첨부파일</th>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("<tr class=\" \" style=\"border:1px solid #dedede\">\r\n");
      out.write("                </tr>\r\n");
      out.write("</tbody>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"ec-base-button \">\r\n");
      out.write("            <span class=\"gLeft\">\r\n");
      out.write("                <a href=\"http://localhost/review/review_my_list.jsp\" class=\"btnNormalFix sizeS\">목록</a>\r\n");
      out.write("            </span>\r\n");
      out.write("            <span class=\"gRight\">\r\n");
      out.write("                <a href=\"review_delete_process.jsp?reviewId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rVO.reviewId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"btnNormalFix sizeS\">삭제</a>\r\n");
      out.write("                <a href=\"http://localhost/review/review_read_frm.jsp?reviewId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rVO.reviewId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&title=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rVO.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&content=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rVO.content }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&currentPage=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty param.currentPage ?1:param.currentPage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"btnEmFix sizeS \">수정</a>\r\n");
      out.write("            </span>\r\n");
      out.write("        </div>\r\n");
      out.write("</div>\r\n");
      out.write("</form></div>\r\n");
      out.write("</div>\r\n");
      out.write("			<!-- golgolz end -->\r\n");
      out.write("	    \r\n");
      out.write("</div>\r\n");
      out.write("</div>	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /review/review_detail_user.jsp(132,59) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rVO.defaultImg}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent(null);
      // /review/review_detail_user.jsp(134,29) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rVO.name}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f2_reused = false;
    try {
      _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f2.setParent(null);
      // /review/review_detail_user.jsp(161,32) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rVO.title}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
      if (_jspx_th_c_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      _jspx_th_c_005fout_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f3_reused = false;
    try {
      _jspx_th_c_005fout_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f3.setParent(null);
      // /review/review_detail_user.jsp(165,32) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rVO.id}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f3 = _jspx_th_c_005fout_005f3.doStartTag();
      if (_jspx_th_c_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
      _jspx_th_c_005fout_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent(null);
      // /review/review_detail_user.jsp(172,53) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rVO.inputDate}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /review/review_detail_user.jsp(172,53) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy-MM-dd EEEE HH:mm:ss");
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f4 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f4_reused = false;
    try {
      _jspx_th_c_005fout_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f4.setParent(null);
      // /review/review_detail_user.jsp(175,57) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ rVO.content }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f4 = _jspx_th_c_005fout_005f4.doStartTag();
      if (_jspx_th_c_005fout_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f4);
      _jspx_th_c_005fout_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f4_reused);
    }
    return false;
  }
}
