/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-05-16 14:35:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.assets.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  public java.lang.String getServletInfo() {
    return "";
  }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      out.write("<div id=\"mheader\" class=\"cboth\">\n");
      out.write("      <div class=\"header_sec02\">\n");
      out.write("        <div class=\"inner\">\n");
      out.write("          <!-- 상단 로고 -->\n");
      out.write("          <div class=\"top_logo\">\n");
      out.write("            <a href=\"http://localhost/index.jsp\"\n");
      out.write("              ><img src=\"http://localhost/assets/images/top_logo.png\"\n");
      out.write("            /></a>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"top_comm\">\n");
      out.write("            <ul>\n");
      out.write("              <!-- 상단 추가메뉴 01 -->\n");
      out.write("              <!-- 로그인 상태에 따라 링크를 동적으로 렌더링 -->\n");
      out.write("                    ");

                    String userId = (String) session.getAttribute("userId");
                    if (userId != null) {
                        // 사용자가 로그인한 경우: 로그아웃 링크를 포함
                        
      out.write("\n");
      out.write("                        <li class=\"xans-element- xans-layout xans-layout-statelogon\">\n");
      out.write("                            <a href=\"http://localhost/user/login/userLogout.jsp\">LOGOUT</a>\n");
      out.write("                        </li>\n");
      out.write("                    ");

                    } else {
                        // 사용자가 로그인하지 않은 경우: 로그인 링크를 포함
                        
      out.write("\n");
      out.write("                        <li class=\"xans-element- xans-layout xans-layout-statelogoff\">\n");
      out.write("                            <a href=\"http://localhost/user/login/userLogin.jsp\">LOGIN</a>\n");
      out.write("                        </li>\n");
      out.write("                    ");

                    }
                    
      out.write("\n");
      out.write("                    ");

                    if (userId != null) {
                    
      out.write("\n");
      out.write("              <li>\n");
      out.write("                <a href=\"http://localhost/user/mypage/mypage.jsp\">MYPAGE</a>\n");
      out.write("              </li>\n");
      out.write("              ");

                    } else {
              
      out.write("\n");
      out.write("              <li>\n");
      out.write("                  <a href=\"#\" onclick=\"loginAlert()\">MYPAGE</a>\n");
      out.write("              </li>\n");
      out.write("              <script type=\"text/javascript\">\n");
      out.write("                  function loginAlert() {\n");
      out.write("                      alert(\"로그인이 필요합니다.\");\n");
      out.write("                      window.location.href = \"http://localhost/user/login/userLogin.jsp\";\n");
      out.write("                  }\n");
      out.write("              </script>\n");
      out.write("          ");

          }
          
      out.write("\n");
      out.write("              <li>\n");
      out.write("                <a href=\"http://localhost/user/OrderReturn/order_list.jsp\"\n");
      out.write("                  >ORDER</a\n");
      out.write("                >\n");
      out.write("              </li>\n");
      out.write("              <li>\n");
      out.write("                <a href=\"http://localhost/cart/cart.jsp\">CART</a>\n");
      out.write("              </li>\n");
      out.write("              <li>\n");
      out.write("                <a href=\"http://localhost/wishlist/wishlist.jsp\">WISH</a>\n");
      out.write("              </li>\n");
      out.write("              <li>\n");
      out.write("                <a href=\"http://localhost/notice/notice.jsp\">NOTICE</a>\n");
      out.write("              </li>\n");
      out.write("            </ul>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <br />\n");
      out.write("      </div>\n");
      out.write("      <!-- header_sec02 -->\n");
      out.write("\n");
      out.write("      <div class=\"header_sec03\" id=\"comment_top\">\n");
      out.write("        <div class=\"inner\">\n");
      out.write("          <!-- 상단 카테고리 : 자동출력 -->\n");
      out.write("          <ul class=\"fleft top_cate\">\n");
      out.write("            <div id=\"mcategory\">\n");
      out.write("              <div id=\"slideCateList\">\n");
      out.write("                <!-- 상단카테고리 자동출력 -->\n");
      out.write("                <ul\n");
      out.write("                  class=\"xans-element- xans-layout xans-layout-category categoryList\"\n");
      out.write("                >\n");
      out.write("                  <li class=\"noChild\">\n");
      out.write("                    <a\n");
      out.write("                      href=\"http://localhost/goods/category.jsp?category=new&page=1\"\n");
      out.write("                      class=\"cate\"\n");
      out.write("                      cate=\"?cate_no=427\"\n");
      out.write("                      >NEW</a\n");
      out.write("                    >\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"noChild\">\n");
      out.write("                    <a\n");
      out.write("                      href=\"http://localhost/goods/category.jsp?category=best&page=1\"\n");
      out.write("                      class=\"cate\"\n");
      out.write("                      cate=\"?cate_no=428\"\n");
      out.write("                      >BEST</a\n");
      out.write("                    >\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"xans-record-\">\n");
      out.write("                    <a\n");
      out.write("                      href=\"http://localhost/goods/category.jsp?category=samsung&page=1\"\n");
      out.write("                      class=\"cate\"\n");
      out.write("                      cate=\"?cate_no=44\"\n");
      out.write("                      >MODEL</a\n");
      out.write("                    >\n");
      out.write("                    <ul class=\"slideSubMenu\">\n");
      out.write("                      <li class=\"xans-record-\" id=\"cate119\">\n");
      out.write("                        <a\n");
      out.write("                      	  href=\"http://localhost/goods/category.jsp?category=samsung&page=1\"\n");
      out.write("                          class=\"cate\"\n");
      out.write("                          cate=\"?cate_no=119\"\n");
      out.write("                          onmouseover=\"subMenuon(this);\"\n");
      out.write("                          >삼성</a\n");
      out.write("                        >\n");
      out.write("                        <ul class=\"slideSubMenu\">\n");
      out.write("                          <li class=\"xans-record-\" id=\"cate119\">\n");
      out.write("                            <a\n");
      out.write("                      	  	  href=\"http://localhost/goods/category.jsp?category=samsung&sub_category=zflip&page=1\"\n");
      out.write("                              class=\"cate\"\n");
      out.write("                              cate=\"?cate_no=119\"\n");
      out.write("                              onmouseover=\"subMenuon(this);\"\n");
      out.write("                              >ZFLIP</a\n");
      out.write("                            >\n");
      out.write("                          </li>\n");
      out.write("                          <li class=\"noChild\" id=\"cate71\">\n");
      out.write("                            <a\n");
      out.write("                      	  	  href=\"http://localhost/goods/category.jsp?category=samsung&sub_category=s24&page=1\"\n");
      out.write("                              class=\"cate\"\n");
      out.write("                              cate=\"?cate_no=71\"\n");
      out.write("                              onmouseover=\"subMenuon(this);\"\n");
      out.write("                              >S24</a\n");
      out.write("                            >\n");
      out.write("                          </li>\n");
      out.write("                        </ul>\n");
      out.write("                      </li>\n");
      out.write("                      <li class=\"xans-record-\" id=\"cate71\">\n");
      out.write("                        <a\n");
      out.write("                      	  href=\"http://localhost/goods/category.jsp?category=apple&page=1\"\n");
      out.write("                          class=\"cate\"\n");
      out.write("                          cate=\"?cate_no=71\"\n");
      out.write("                          onmouseover=\"subMenuon(this);\"\n");
      out.write("                          >애플</a\n");
      out.write("                        >\n");
      out.write("                        <ul class=\"slideSubMenu\">\n");
      out.write("                          <li class=\"noChild\">\n");
      out.write("                            <a\n");
      out.write("                              href=\"http://localhost/goods/category.jsp?category=apple&sub_category=아이폰14&page=1\"\n");
      out.write("                              class=\"cate\"\n");
      out.write("                              cate=\"?cate_no=119\"\n");
      out.write("                              onmouseover=\"subMenuon(this);\"\n");
      out.write("                              >아이폰14</a\n");
      out.write("                            >\n");
      out.write("                          </li>\n");
      out.write("                          <li class=\"noChild\" id=\"cate71\">\n");
      out.write("                            <a\n");
      out.write("                              href=\"http://localhost/goods/category.jsp?category=apple&sub_category=아이폰15&page=1\"\n");
      out.write("                              class=\"cate\"\n");
      out.write("                              cate=\"?cate_no=71\"\n");
      out.write("                              onmouseover=\"subMenuon(this);\"\n");
      out.write("                              >아이폰15</a\n");
      out.write("                            >\n");
      out.write("                          </li>\n");
      out.write("                        </ul>\n");
      out.write("                      </li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"xans-record-\">\n");
      out.write("                    <a\n");
      out.write("                      href=\"http://localhost/goods/category.jsp?category=실리콘&page=1\"\n");
      out.write("                      class=\"cate\"\n");
      out.write("                      cate=\"?cate_no=44\"\n");
      out.write("                      >MATERIAL</a\n");
      out.write("                    >\n");
      out.write("                    <ul class=\"slideSubMenu\">\n");
      out.write("                      <li class=\"noChild\">\n");
      out.write("                        <a\n");
      out.write("                      	  href=\"http://localhost/goods/category.jsp?category=실리콘&page=1\"\n");
      out.write("                          class=\"cate\"\n");
      out.write("                          cate=\"?cate_no=45\"\n");
      out.write("                          >실리콘</a\n");
      out.write("                        >\n");
      out.write("                      </li>\n");
      out.write("                      <li class=\"noChild\">\n");
      out.write("                        <a\n");
      out.write("                      	  href=\"http://localhost/goods/category.jsp?category=하드&page=1\"\n");
      out.write("                          class=\"cate\"\n");
      out.write("                          cate=\"?cate_no=47\"\n");
      out.write("                          >하드</a\n");
      out.write("                        >\n");
      out.write("                      </li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                </ul>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- //mcategory -->\n");
      out.write("          </ul>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <!-- header_sec03 -->\n");
      out.write("    </div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
