/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-05-16 14:35:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import user.main.GoodsSimpleVO;
import java.util.List;
import user.main.UserMainDAO;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  public java.lang.String getServletInfo() {
    return "";
  }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("user.main.GoodsSimpleVO");
    _jspx_imports_classes.add("user.main.UserMainDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./assets/jsp/user/lib.jsp", out, false);
      out.write("\n");
      out.write("	<!-- golgolz start -->\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("      $(function () {\n");
      out.write("        $(\".carousel-slides\").slick({\n");
      out.write("          infinite: true,\n");
      out.write("          speed: 500,\n");
      out.write("          fade: true,\n");
      out.write("          autoplay: true,\n");
      out.write("          autoplaySpeed: 2000,\n");
      out.write("          arrows: true,\n");
      out.write("          prevArrow: $(\".carousel-prev\"),\n");
      out.write("          nextArrow: $(\".carousel-next\"),\n");
      out.write("        });\n");
      out.write("        \n");
      out.write("		$(\".need_login\").click(function(event){\n");
      out.write("		 	$.ajax({\n");
      out.write("		        url: \"http://localhost/goods/check_login.jsp\",\n");
      out.write("		        type: \"GET\",\n");
      out.write("		        dataType: \"JSON\",\n");
      out.write("		        error: function(xhr){\n");
      out.write("		        	alert(\"로그인 체크 실패\" + xhr.status);\n");
      out.write("		        },\n");
      out.write("		        success: function(response) {\n");
      out.write("		             if (!response.flag) {\n");
      out.write("		     			event.preventDefault();\n");
      out.write("		                //alert('로그인이 필요합니다.');\n");
      out.write("		                location.href = 'http://localhost/user/login/userLogin.jsp';\n");
      out.write("		            } \n");
      out.write("		        }\n");
      out.write("		    });\n");
      out.write("		});\n");
      out.write("      });\n");
      out.write("    </script>\n");
      out.write("    <link\n");
      out.write("      rel=\"stylesheet\"\n");
      out.write("      type=\"text/css\"\n");
      out.write("      href=\"//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css\"/>\n");
      out.write("    <script\n");
      out.write("      type=\"text/javascript\"\n");
      out.write("      src=\"//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js\"></script>\n");
      out.write("	<link href=\"./assets/css/index.css\" rel=\"stylesheet\" />\n");
      out.write("	<!-- golgolz end -->\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	");

		UserMainDAO userMainDAO = UserMainDAO.getInstance();
		List<GoodsSimpleVO> newGoods = userMainDAO.selectGoods(true);
		List<GoodsSimpleVO> bestGoods = userMainDAO.selectGoods(false);
	
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./assets/jsp/user/header.jsp", out, false);
      out.write("\n");
      out.write("	<div id=\"wrap\">\n");
      out.write("		<div id=\"main\">\n");
      out.write("			<!-- golgolz start -->\n");
      out.write("			<div class=\"carousel\">\n");
      out.write("				<span class=\"carousel-prev\">\n");
      out.write("					<img src=\"http://localhost/assets/images/index/left-arrow.png\" />\n");
      out.write("				</span>\n");
      out.write("          		<div class=\"carousel-slides\">\n");
      out.write("					");
 
						GoodsSimpleVO tempVO = null;
						for(int i = 0; i < 5; i++){ 
						    tempVO = bestGoods.get(i);
					
      out.write("\n");
      out.write("					<div class=\"carousel-slide\">\n");
      out.write("		            	<!-- 메인 키비주얼 01 : 링크수정 -->\n");
      out.write("		              	<a href=\"http://localhost/goods/detail.jsp?goods=");
      out.print( tempVO.getCode() );
      out.write("\">\n");
      out.write("		              		<div class=\"img\">\n");
      out.write("		                  		<img \n");
      out.write("		                  		src=\"http://localhost/assets/images/goods/");
      out.print( tempVO.getDefaultImage() );
      out.write("\" \n");
      out.write("                    			style=\"width: 50%; margin: 0px auto\"/>\n");
      out.write("		                	</div>\n");
      out.write("		                	<div class=\"swiper1_txt\">\n");
      out.write("		                  		<div class=\"inner\">\n");
      out.write("		                    	<!-- 메인 키비주얼 01 : 텍스트 수정 -->\n");
      out.write("		                    		<div class=\"t01\">");
      out.print( tempVO.getName() );
      out.write("</div>\n");
      out.write("		                    		<div class=\"t02\">");
      out.print( tempVO.getDetailDescription() );
      out.write("</div>\n");
      out.write("		                    		<div class=\"t03\">");
      out.print( tempVO.getPrice() );
      out.write("</div>\n");
      out.write("		                  		</div>\n");
      out.write("		                	</div>\n");
      out.write("		              	</a>\n");
      out.write("		         	</div>\n");
      out.write("					");
 } 
      out.write("\n");
      out.write("            	</div>\n");
      out.write("				<span class=\"carousel-next\">\n");
      out.write("					<img src=\"http://localhost/assets/images/index/right-arrow.png\" />\n");
      out.write("				</span>\n");
      out.write("        	</div>\n");
      out.write("        	<div class=\"main_pro_title cboth\">\n");
      out.write("				<div class=\"txt_01\">NEW ARRIVAL</div>\n");
      out.write("				<div class=\"txt_02\">오브젝트에 새롭게 들어온 제품을 소개합니다.</div>\n");
      out.write("			</div>\n");
      out.write("		    <div class=\"xans-element- xans-product xans-product-listmain-2 xans-product-listmain xans-product-2 ec-base-product typeThumb sort_pro\">\n");
      out.write("		        <ul class=\"prdList grid5\">\n");
      out.write("		        	");

		        		for(GoodsSimpleVO goods : newGoods){
		        	
      out.write("\n");
      out.write("		            <li id=\"anchorBoxId_6371\" class=\"xans-record-\">\n");
      out.write("		                <div class=\"box\">\n");
      out.write("		                    <div class=\"thumbnail\">\n");
      out.write("		                        <div class=\"prdImg\">\n");
      out.write("		                            <a href=\"http://localhost/goods/detail.jsp?goods=");
      out.print( goods.getCode() );
      out.write("\" name=\"anchorBoxName_6371\">\n");
      out.write("		                                <img src=\"http://localhost/assets/images/goods/");
      out.print( goods.getDefaultImage() );
      out.write("\" id=\"eListPrdImage6371_3\" alt=\"[오브젝트] 2024 오브젝트 다이어리 (날짜형)\">\n");
      out.write("		                            </a>\n");
      out.write("		                        </div>\n");
      out.write("		                        <span class=\"wish\">\n");
      out.write("		                        	<a href=\"http://localhost/wishlist/wishlist_insert_process.jsp?code=");
      out.print( goods.getCode() );
      out.write("\" class=\"need_login\">\n");
      out.write("		                            	<img src=\"http://localhost/assets/images/index/like_icon.png\" class=\"icon_img ec-product-listwishicon\" alt=\"관심상품 등록\">\n");
      out.write("		                            </a>\n");
      out.write("		                        </span>\n");
      out.write("		                    </div>\n");
      out.write("		                    <div class=\"description\">\n");
      out.write("		                        <div class=\"name\">\n");
      out.write("		                            <a href=\"http://localhost/goods/detail.jsp\" class=\"\">\n");
      out.write("		                                <span style=\"font-size:12px;color:#000000;\">");
      out.print( goods.getName() );
      out.write("</span>\n");
      out.write("		                            </a>\n");
      out.write("		                        </div>\n");
      out.write("		                        <ul class=\"xans-element- xans-product xans-product-listitem-2 xans-product-listitem xans-product-2 spec\">\n");
      out.write("		                            <li class=\" xans-record-\">\n");
      out.write("		                                <span style=\"font-size:12px;color:#000000;font-weight:bold;\">");
      out.print( goods.getPrice() );
      out.write("원</span>\n");
      out.write("		                            </li>\n");
      out.write("		                        </ul>\n");
      out.write("		                    </div>\n");
      out.write("		                </div>\n");
      out.write("		            </li>\n");
      out.write("		            ");
 } 
      out.write("\n");
      out.write("		        </ul>\n");
      out.write("		    </div>\n");
      out.write("		    <div class=\"main_pro_title cboth\">\n");
      out.write("				<div class=\"txt_01\">BEST ITEMS</div>\n");
      out.write("				<div class=\"txt_02\">오브젝트의 인기 제품을 소개합니다.</div>\n");
      out.write("			</div>\n");
      out.write("		    <div class=\"xans-element- xans-product xans-product-listmain-2 xans-product-listmain xans-product-2 ec-base-product typeThumb sort_pro\">\n");
      out.write("		        <ul class=\"prdList grid5\">\n");
      out.write("		        	");

		        		for(GoodsSimpleVO goods : bestGoods){
		        	
      out.write("\n");
      out.write("		            <li id=\"anchorBoxId_6371\" class=\"xans-record-\">\n");
      out.write("		                <div class=\"box\">\n");
      out.write("		                    <div class=\"thumbnail\">\n");
      out.write("		                        <div class=\"prdImg\">\n");
      out.write("		                            <a href=\"http://localhost/goods/detail.jsp?goods=");
      out.print( goods.getCode() );
      out.write("\" name=\"anchorBoxName_6371\">\n");
      out.write("		                                <img src=\"http://localhost/assets/images/goods/");
      out.print( goods.getDefaultImage() );
      out.write("\" id=\"eListPrdImage6371_3\" alt=\"");
      out.print( goods.getName() );
      out.write("\">\n");
      out.write("		                            </a>\n");
      out.write("		                        </div>\n");
      out.write("		                        <span class=\"wish\">\n");
      out.write("		                        	<a href=\"http://localhost/wishlist/wishlist.jsp?code=");
      out.print( goods.getCode() );
      out.write("\">\n");
      out.write("		                            	<img src=\"http://localhost/assets/images/index/like_icon.png\" class=\"icon_img ec-product-listwishicon\" alt=\"관심상품 등록\">\n");
      out.write("		                            </a>\n");
      out.write("		                        </span>\n");
      out.write("		                    </div>\n");
      out.write("		                    <div class=\"description\">\n");
      out.write("		                        <div class=\"name\">\n");
      out.write("		                            <a href=\"http://localhost/goods/detail.jsp\" class=\"\">\n");
      out.write("		                                <span style=\"font-size:12px;color:#000000;\">");
      out.print( goods.getName() );
      out.write("</span>\n");
      out.write("		                            </a>\n");
      out.write("		                        </div>\n");
      out.write("		                        <ul class=\"xans-element- xans-product xans-product-listitem-2 xans-product-listitem xans-product-2 spec\">\n");
      out.write("		                            <li class=\" xans-record-\">\n");
      out.write("		                                <span style=\"font-size:12px;color:#000000;font-weight:bold;\">");
      out.print( goods.getPrice() );
      out.write("원</span>\n");
      out.write("		                            </li>\n");
      out.write("		                        </ul>\n");
      out.write("		                    </div>\n");
      out.write("		                </div>\n");
      out.write("		            </li>\n");
      out.write("		            ");
 } 
      out.write("\n");
      out.write("		        </ul>\n");
      out.write("		    </div>\n");
      out.write("			<!-- golgolz end -->\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
